### ISSUE TITLE
NullReferenceException in HeartBeat

### ISSUE THREAD

**Issue by jamesblack** [jbruening/PNet#8]
I cloned your code, I made sure to use the exact revision of Lidgren you are talking about, and I followed all the instructions about slimmath and such.

 However when I run the code it seems to be working, until I connect a client. At which point I get a constant flow of errors

```
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at Lidgren.Network.NetConnection.Heartbeat(Single now, UInt32 frameCounter) i
n d:\Development\Olympus\Server\PNet\Lidgren.Network\NetConnection.cs:line 260
   at Lidgren.Network.NetPeer.Heartbeat() in d:\Development\Olympus\Server\PNet\
Lidgren.Network\NetPeer.Internal.cs:line 383
   at Lidgren.Network.NetPeer.NetworkLoop() in d:\Development\Olympus\Server\PNe
t\Lidgren.Network\NetPeer.Internal.cs:line 228
```

I am using your example server/example client, and this is the error I am getting, no customization. Am I doing something wrong that might not be documented?

**Comment by jbruening** [comment]
can you let the debugger stop on that exception and examine what is null? I have a feeling this is an issue with lidgren.

**Comment by jamesblack** [comment]
Channel I what is coming up null, thanks for the quick response

**Comment by jamesblack** [comment]
I dont know enough about the lidgren innards to know whats going on, but this doesn't seem to be happening I just use lidgren? Is it a integration thing?

**Comment by d3n4** [comment]
Same problem

**Comment by d3n4** [comment]
### Resolved. 
Fix: in file **NetConnection.cs** after line (**258**)
```C#
var channel = m_sendChannels[i];
```
add:
```C#
if (channel == null)
    continue;
```
